"""Initial database schema for SQLite

Revision ID: ea9a352bef9d
Revises: 
Create Date: 2025-12-09 23:03:04.890788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9a352bef9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('cognitive_load', sa.Float(), nullable=True),
    sa.Column('key_terms', sa.JSON(), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('multimedia_resources', sa.JSON(), nullable=True),
    sa.Column('interactive_elements', sa.JSON(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('assessment_criteria', sa.JSON(), nullable=True),
    sa.Column('practical_applications', sa.JSON(), nullable=True),
    sa.Column('real_world_examples', sa.JSON(), nullable=True),
    sa.Column('common_misconceptions', sa.JSON(), nullable=True),
    sa.Column('teaching_strategies', sa.JSON(), nullable=True),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('usage_frequency', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('average_completion_time', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('content_quality_score', sa.Float(), nullable=True),
    sa.Column('ai_generated_content', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('concept_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('learning_style', sa.String(length=20), nullable=True),
    sa.Column('skill_level', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('concept_relations',
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('related_concept_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['related_concept_id'], ['concepts.concept_id'], ),
    sa.PrimaryKeyConstraint('concept_id', 'related_concept_id')
    )
    op.create_table('learning_paths',
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('target_audience', sa.String(length=100), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('adaptive', sa.Boolean(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('learning_outcomes', sa.JSON(), nullable=True),
    sa.Column('assessment_points', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_table('quizzes',
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('randomize_questions', sa.Boolean(), nullable=True),
    sa.Column('show_correct_answers', sa.Boolean(), nullable=True),
    sa.Column('allow_review', sa.Boolean(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.concept_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('user_achievements',
    sa.Column('achievement_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('achievement_type', sa.String(length=50), nullable=False),
    sa.Column('achievement_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('badge_icon', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    op.create_index('idx_achievement_category', 'user_achievements', ['category'], unique=False)
    op.create_index('idx_achievement_type', 'user_achievements', ['achievement_type'], unique=False)
    op.create_index('idx_achievement_user', 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_learning_preferences',
    sa.Column('preference_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content_type_preferences', sa.JSON(), nullable=True),
    sa.Column('difficulty_preferences', sa.JSON(), nullable=True),
    sa.Column('subject_preferences', sa.JSON(), nullable=True),
    sa.Column('study_time_preferences', sa.JSON(), nullable=True),
    sa.Column('session_length_preferences', sa.Integer(), nullable=True),
    sa.Column('interaction_preferences', sa.JSON(), nullable=True),
    sa.Column('feedback_preferences', sa.JSON(), nullable=True),
    sa.Column('accessibility_needs', sa.JSON(), nullable=True),
    sa.Column('personalization_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_table('learning_path_concepts',
    sa.Column('path_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('required_mastery_level', sa.Float(), nullable=True),
    sa.Column('adaptive_difficulty', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.path_id'], ),
    sa.PrimaryKeyConstraint('path_id', 'concept_id')
    )
    op.create_table('learning_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('path_id', sa.String(length=36), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_concept_id', sa.String(length=36), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('concepts_completed', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True),
    sa.Column('difficulty_adjustments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['current_concept_id'], ['concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.path_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('quiz_attempts',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('difficulty_rating', sa.Float(), nullable=True),
    sa.Column('confusion_areas', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index('idx_attempt_score', 'quiz_attempts', ['score'], unique=False)
    op.create_index('idx_attempt_user_quiz', 'quiz_attempts', ['user_id', 'quiz_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('progress_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('mastery_level', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('first_attempt', sa.DateTime(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('review_interval', sa.Integer(), nullable=True),
    sa.Column('learning_velocity', sa.Float(), nullable=True),
    sa.Column('struggling_areas', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_index('idx_progress_mastery', 'user_progress', ['mastery_level'], unique=False)
    op.create_index('idx_progress_next_review', 'user_progress', ['next_review_date'], unique=False)
    op.create_index('idx_progress_user_concept', 'user_progress', ['user_id', 'concept_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_progress_user_concept', table_name='user_progress')
    op.drop_index('idx_progress_next_review', table_name='user_progress')
    op.drop_index('idx_progress_mastery', table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index('idx_attempt_user_quiz', table_name='quiz_attempts')
    op.drop_index('idx_attempt_score', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_table('learning_sessions')
    op.drop_table('learning_path_concepts')
    op.drop_table('user_learning_preferences')
    op.drop_index('idx_achievement_user', table_name='user_achievements')
    op.drop_index('idx_achievement_type', table_name='user_achievements')
    op.drop_index('idx_achievement_category', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_table('quizzes')
    op.drop_table('learning_paths')
    op.drop_table('concept_relations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('concepts')
    # ### end Alembic commands ###
